
from newreportapp.forms.user.user_registration_form import UserRegistrationForm
from newreportapp.forms.user.user_profile_form import UserProfileForm, CustomPasswordChangeForm
from newreportapp.forms.comment_post_form import CommentForm