# Generated by Django 5.1.2 on 2024-10-30 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0002_customusermodel_display_name_customusermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='friends_pending',
            field=models.ManyToManyField(blank=True, related_name='pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
