# Generated by Django 5.1.2 on 2024-10-30 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0005_customusermodel_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
