# Generated by Django 5.1.2 on 2024-10-31 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0008_alter_customusermodel_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='confirmation_token',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
