# Generated by Django 5.1.2 on 2024-11-01 09:09

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0010_alter_postmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='user_photos/', variations={'large': (300, 300), 'thumbnail': (100, 100, True)}),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(blank=True, default='Imagem e Descrição', max_length=200, verbose_name='Título'),
        ),
    ]
