# Generated by Django 5.1.2 on 2024-11-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0011_customusermodel_photo_alter_postmodel_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='friends_pending',
        ),
    ]
