# Generated by Django 5.1.2 on 2024-11-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0012_remove_customusermodel_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='privacy',
            field=models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='public', max_length=20),
        ),
    ]
