# Generated by Django 5.1.2 on 2024-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0014_comentpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('moderador', 'moderador'), ('administrator', 'Administrator')], default='viewer', max_length=20),
        ),
    ]
