# Generated by Django 5.1.2 on 2024-11-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0020_postmodel_set_as_inappropriate'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='accept_comments',
            field=models.BooleanField(default=True, verbose_name='Aceita comentários'),
        ),
    ]
