# Generated by Django 5.1.2 on 2024-11-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0021_postmodel_accept_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='accept_comments',
        ),
    ]
