# Generated by Django 5.1.2 on 2024-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0022_remove_postmodel_accept_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('moderador', 'Moderador'), ('administrator', 'Administrador')], default='viewer', max_length=20),
        ),
    ]
