# Generated by Django 5.1.2 on 2024-11-06 18:58

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0023_alter_customusermodel_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='user_photos/', variations={}),
        ),
    ]
