# Generated by Django 5.1.2 on 2024-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0024_alter_customusermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('moderator', 'Moderador'), ('administrator', 'Administrador')], default='viewer', max_length=20),
        ),
    ]
