# Generated by Django 5.1.2 on 2024-11-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0026_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentpostmodel',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
