# Generated by Django 5.1.2 on 2024-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0027_alter_comentpostmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='set_as_prohibited',
            field=models.BooleanField(default=False, verbose_name='Marcado como proibido'),
        ),
    ]
