# Generated by Django 5.1.2 on 2024-11-10 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0029_alter_customusermodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('designation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Designação')),
                ('occurrence_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da Ocorrência')),
                ('occurrence_time', models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Atendimento')),
                ('call_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Acionamento')),
                ('call_time', models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Acionamento')),
                ('service_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Atendimento')),
                ('service_time', models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Atendimento')),
                ('report_number', models.CharField(default='', max_length=100, null=True, verbose_name='Número do Laudo')),
                ('city', models.CharField(default='Limeira', max_length=100, null=True, verbose_name='Cidade')),
                ('protocol_number', models.CharField(default='', max_length=200, null=True, verbose_name='Número do Protocolo')),
                ('police_report_number', models.CharField(default='', max_length=200, null=True, verbose_name='Número do Boletim de Ocorrência')),
                ('examination_objective', models.CharField(default='', max_length=300, verbose_name='Objetivo do Exame')),
                ('incident_nature', models.CharField(default='', max_length=300, null=True, verbose_name='Natureza da Ocorrência')),
                ('police_station', models.CharField(default='', max_length=200, null=True, verbose_name='Distrito Policial')),
                ('requesting_authority', models.CharField(default='', max_length=200, null=True, verbose_name='Autoridade Requisitante')),
                ('institute_director', models.CharField(default='', max_length=200, verbose_name='Diretor do Instituto')),
                ('institute_unit', models.CharField(default='', max_length=200, verbose_name='Núcleo do Instituto')),
                ('forensic_team_base', models.CharField(default='', max_length=200, verbose_name='Base da Equipe de Perícias')),
                ('expert_display_name', models.CharField(default='', max_length=200, verbose_name='Perito')),
                ('considerations', models.TextField(blank=True, default='', verbose_name='Considerações')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='Conclusão')),
                ('reporting_expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Perito Relator')),
            ],
            options={
                'verbose_name': 'Relatório Pericial',
                'verbose_name_plural': 'Relatórios Periciais',
            },
        ),
    ]
