# Generated by Django 5.1.2 on 2024-11-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0030_headerreportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributesToReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('director', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('unit', models.CharField(default='', max_length=150)),
                ('team', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Attribute to Report',
                'verbose_name_plural': 'User Attributes to Report',
            },
        ),
    ]
