# Generated by Django 5.1.2 on 2024-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0031_userattributestoreportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('moderator', 'Moderador'), ('administrator', 'Administrador')], default='viewer', max_length=20),
        ),
    ]
