# Generated by Django 5.1.2 on 2024-11-12 19:49

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0032_customusermodel_is_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('subject', models.CharField(choices=[('local', 'Local'), ('veiculo', 'Veículo'), ('peça', 'Peça'), ('cadáver', 'Cadáver'), ('impressao_digital', 'Impressão Digital'), ('sangue', 'Sangue'), ('remessa_ra', 'Remessa para RA'), ('remessa_autoridade', 'Remessa para Autoridade'), ('outro', 'Outro')], max_length=20, verbose_name='Assunto')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('header_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='newreportapp.headerreportmodel', verbose_name='Cabeçalho do Relatório')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='newreportapp.sectionreportmodel', verbose_name='Seção Pai')),
            ],
            options={
                'verbose_name': 'Seção do Relatório',
                'verbose_name_plural': 'Seções do Relatório',
                'ordering': ['order'],
                'unique_together': {('header_report', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ImageReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='report_images/', variations={}, verbose_name='Imagem')),
                ('caption', models.CharField(max_length=255, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('report_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newreportapp.sectionreportmodel', verbose_name='Seção do Relatório')),
            ],
            options={
                'verbose_name': 'Imagem da Seção do Relatório',
                'verbose_name_plural': 'Imagens da Seção do Relatório',
                'ordering': ['order'],
            },
        ),
    ]
