# Generated by Django 5.1.2 on 2024-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0033_sectionreportmodel_imagereportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome para exibição'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Não informar')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='sectionreportmodel',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Assunto'),
        ),
    ]
