# Generated by Django 5.1.2 on 2024-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0034_alter_customusermodel_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionreportmodel',
            name='rota',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='url'),
        ),
    ]
