# Generated by Django 5.1.2 on 2024-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0035_sectionreportmodel_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereportmodel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
    ]
