# Generated by Django 5.1.2 on 2024-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0036_imagereportmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerreportmodel',
            name='photographer',
            field=models.CharField(default='', max_length=200, verbose_name='Fotografia'),
        ),
    ]
