# Generated by Django 5.1.2 on 2024-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0037_headerreportmodel_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionreportmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
