# Generated by Django 5.1.2 on 2024-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newreportapp', '0038_alter_sectionreportmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereportmodel',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subtítulo'),
        ),
    ]
